apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007 # Optional, otherwise a random port in range 30000-32767 is assigned
  type: NodePort    
  selector:
    app: guestbook-ui
